definitions:
  services:
    docker:
      memory: 4096

pipelines:
  branches:
    develop:
      - step:
          name: flying-pub
          size: 2x
          services:
            - docker
          script:
            - echo -e 'Host 192.168.0.*\n\tUser huoju\n\tForwardAgent yes\n\tProxyCommand ssh huoju@139.198.2.168 nc %h %p' >> ~/.ssh/config && ssh -o StrictHostKeyChecking=no huoju@192.168.0.3 "cd ./build_shortcuts && ./28_build_flying_pub_dev.sh"

    release:
      - step:
          name: flying-pub
          size: 2x
          services:
            - docker
          script:
            - echo -e 'Host 192.168.0.*\n\tUser huoju\n\tForwardAgent yes\n\tProxyCommand ssh huoju@139.198.2.168 nc %h %p' >> ~/.ssh/config && ssh -o StrictHostKeyChecking=no huoju@192.168.0.3 "cd ./build_shortcuts && ./14_build_pub.sh"
