definitions:
  services:
    docker:
      memory: 4096

pipelines:
  branches:
    master:
      - step:
          name: medium
          size: 2x
          services:
            - docker
          caches:
            - docker
          script:
            - export IMAGE_NAME=$DOCKER_REGISTRY_DOMAIN/$DOCKER_REGISTRY_USERNAME/medium:$BITBUCKET_BRANCH
            - docker build -f Dockerfile-test -t $IMAGE_NAME .
            - docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_DOMAIN
            - docker push $IMAGE_NAME
    release:
      - step:
          name: medium
          size: 2x
          services:
            - docker
          script:
            - ssh -J huoju@139.198.2.168 huoju@192.168.0.3 "sudo chmod 755 -R build_shortcuts && cd ./build_shortcuts && ./15_build_medium.sh"