definitions:
  services:
    docker:
      memory: 4096

pipelines:
  branches:
    release:
      - step:
          name: medium
          size: 2x
          services:
            - docker
          script:
            - echo -e 'Host 192.168.0.*\n\tUser huoju\n\tForwardAgent yes\n\tProxyCommand ssh huoju@139.198.2.168 nc %h %p' >> ~/.ssh/config && ssh -o StrictHostKeyChecking=no huoju@192.168.0.3 "cd ./build_shortcuts && git pull && ./15_build_medium.sh"
