FROM node:10.15.2

ADD . /app

WORKDIR /app/fe
RUN npm install -g -s --no-progress yarn
RUN yarn install
RUN yarn build:staging
RUN mv ./build /app/be/build

WORKDIR /app/be
RUN npm install -g -s --no-progress yarn
RUN yarn install

WORKDIR /app

EXPOSE 5000 9000

CMD chmod 777 *.sh && ./start-prod.sh
